FROM oven/bun:1 AS deps
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

FROM oven/bun:1 AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# 1. Declarar todos los argumentos que envía Easypanel
ARG SQUARE_ACCESS_TOKEN
ARG SQUARE_APPLICATION_ID
ARG SQUARE_LOCATION_ID
ARG SQUARE_ENVIRONMENT
ARG SQUARE_WEBHOOK_NOTIFICATION_URL
ARG GHL_API_BASE_URL
ARG GHL_API_TOKEN
ARG GHL_API_VERSION
ARG GHL_LOCATION_ID
ARG GHL_BLOG_ID
ARG REVALIDATE_SECRET
ARG AUTH_SECRET
ARG AUTH_URL
ARG AUTH_TRUST_HOST
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG SIGNATURE_KEY
ARG N8N_WEBHOOK_URL

# 2. Asignarlos como Variables de Entorno para el Build
ENV SQUARE_ACCESS_TOKEN=$SQUARE_ACCESS_TOKEN
ENV SQUARE_APPLICATION_ID=$SQUARE_APPLICATION_ID
ENV SQUARE_LOCATION_ID=$SQUARE_LOCATION_ID
ENV SQUARE_ENVIRONMENT=$SQUARE_ENVIRONMENT
ENV SQUARE_WEBHOOK_NOTIFICATION_URL=$SQUARE_WEBHOOK_NOTIFICATION_URL
ENV GHL_API_BASE_URL=$GHL_API_BASE_URL
ENV GHL_API_TOKEN=$GHL_API_TOKEN
ENV GHL_API_VERSION=$GHL_API_VERSION
ENV GHL_LOCATION_ID=$GHL_LOCATION_ID
ENV GHL_BLOG_ID=$GHL_BLOG_ID
ENV REVALIDATE_SECRET=$REVALIDATE_SECRET
ENV AUTH_SECRET=$AUTH_SECRET
ENV AUTH_URL=$AUTH_URL
ENV AUTH_TRUST_HOST=$AUTH_TRUST_HOST
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV SIGNATURE_KEY=$SIGNATURE_KEY
ENV N8N_WEBHOOK_URL=$N8N_WEBHOOK_URL
RUN bun run build

FROM node:22-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]